version: '3.8'

services:
  elasticsearch:
    image: trungtvo/custom-elasticsearch:latest
    container_name: es01
    build:
      context: ./
      dockerfile: ./elasticsearch/Dockerfile
    environment:
      - ES_SETTING_CLUSTER_NAME=my-docker-cluster   # same as cluster.name, but prefix with "ES_SETTING_"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elasticnet
  kibana:
    image: trungtvo/custom-kibana:latest
    container_name: kib01
    build:
      context: ./
      dockerfile: ./kibana/Dockerfile
    ports:
      - '5601:5601'
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

networks:
  elasticnet:
    driver: bridge
    name: elasticnet